spring.application.name=consumer


spring.rabbitmq.addresses= amqps://extaytqr:LwOQH7CDgWXg_wBVSEBz2Qs-8ow87_bv@cow.rmq2.cloudamqp.com/extaytqr


spring.datasource.url=jdbc:postgresql://localhost:5432/rabbitmq-in-action/consumer
spring.datasource.password=v3rys3cr3t
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.sentinel.master=mymaster
#sentinel servers
spring.data.redis.sentinel.nodes={localhost:6383,localhost:6384,localhost:6385}
